# Import ToolKit4D Pipeline

In [1]:
from ToolKit4D.pipeline import ToolKitPipeline

# Load Raw images

In [2]:
LA3d0v1 = ToolKitPipeline(rawfile='../raw/LA3_d0_v1_uint16_unnormalised_2028_2028_2028.raw')

Once instantiate, this raw image is loaded as numpy array:

In [3]:
LA3d0v1.raw

array([[[32436, 32436, 32436, ..., 32436, 32436, 32436],
        [32436, 32436, 32436, ..., 32436, 32436, 32436],
        [32436, 32436, 32436, ..., 32436, 32436, 32436],
        ...,
        [32436, 32436, 32436, ..., 32436, 32436, 32436],
        [32436, 32436, 32436, ..., 32436, 32436, 32436],
        [32436, 32436, 32436, ..., 32436, 32436, 32436]],

       [[32436, 32436, 32436, ..., 32436, 32436, 32436],
        [32436, 32436, 32436, ..., 32436, 32436, 32436],
        [32436, 32436, 32436, ..., 32436, 32436, 32436],
        ...,
        [32436, 32436, 32436, ..., 32436, 32436, 32436],
        [32436, 32436, 32436, ..., 32436, 32436, 32436],
        [32436, 32436, 32436, ..., 32436, 32436, 32436]],

       [[32436, 32436, 32436, ..., 32436, 32436, 32436],
        [32436, 32436, 32436, ..., 32436, 32436, 32436],
        [32436, 32436, 32436, ..., 32436, 32436, 32436],
        ...,
        [32436, 32436, 32436, ..., 32436, 32436, 32436],
        [32436, 32436, 32436, ..., 32436, 324

The instantiation process also automatically creates directories under current working directory: `image_folder` and `threshold_folder` to store the processed results from subsequent procedures 

In [4]:
LA3d0v1.image_folder, LA3d0v1.threshold_folder

('./results\\LA3v1d0/image/', './results\\LA3v1d0/threshold/')

Besides raw, image_folder and threshold_folder, Other attributes include instance identifier, image size and image type

In [5]:
LA3d0v1.identifier, LA3d0v1.im_size, LA3d0v1.im_type

('LA3v1d0', [2028, 2028, 2028], 'uint16')

# Processing with the `threshold_rock` Function

In [13]:
LA3d0v1.threshold_rock(save=True)

-----Finding Rock Threshold-----
	 calling threshold_rock()
	 -- calculating histogram ...
	 -- finding otsu threshold ...


Set `save=True` to save the processed image under `image_folder` and threholding values under `threshold_folder`

# Processing with the `remove_cylinder` Function

In [14]:
LA3d0v1.remove_cylinder(save=True)

-----Removing Cylinder-----
	 calling remove_cylinder()
	 -- finding 1 slice circle ...
	 -- finding 2 slice circle ...
	 -- finding slope and incp ...
	 -- removing circles at each slice ...


Again, Set `save=True` to save the result.

# Processing with the `segment_rocks` Function

In [15]:
LA3d0v1.segment_rocks(save=True)

-----Segment Rocks-----
	 calling segment_rocks()
	 -- filtering out small objects ...
	 -- filling holes of the image ...
	 -- finding largest "air" object ...
	 -- do image opening...


# Processing with the `separate_rocks` Function

In [ ]:
LA3d0v1.separate_rocks(model_path='../model/compact_bs32_epoch25_p.pth', ML=True, save=True)

The default `model_path` for `separate_rocks` function is '../model/compact_bs32_epoch25_p.pth'. If you are not at the directory of this notebook, remenber to change the path to the model


# Processing with the `agglomerate_extaction` Function

In [ ]:
LA3d0v1.agglomerate_extraction(save=True)

# Processing with the `threshold_grain` Function

In [ ]:
LA3d0v1.threshold_grain(method='moments', save=True)

# Use Preload Parameter to load processed image to attributes

In [ ]:
del LA3d0v1

In [2]:
LA3d0v1 = ToolKitPipeline(rawfile='../raw/LA3_d0_v1_uint16_unnormalised_2028_2028_2028.raw', load=True)

If the processed images have already been saved in `image_folder`, use the parameter `load=True` can directly load these images to the instance attributes

Here, `rock_thresh_mask ` and `column_mask` are loaded and can be accessed

In [4]:
LA3d0v1.rock_thresh_mask

(array([[[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False]],
 
        [[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False]],
 
        [[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, 

In [5]:
LA3d0v1.column_mask

array([[[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]],

       [[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]],

       [[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, Fal